# Generated by Django 5.2.1 on 2025-05-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='book_photos/')),
                ('isbn', models.IntegerField()),
                ('yop', models.DateField()),
                ('ph', models.CharField(max_length=100)),
                ('pageNum', models.IntegerField()),
                ('dimensions', models.IntegerField()),
                ('type', models.CharField(choices=[('S', 'SOFT'), ('H', 'HARD')], max_length=1)),
                ('cat', models.CharField(choices=[('ROM', 'ROMANCE'), ('THR', 'THRILLER'), ('BIO', 'BIOGRAPHY'), ('CLA', 'CLASSIC'), ('DRA', 'DRAMA'), ('HIS', 'HISTORY')], max_length=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PublishingHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('website', models.CharField()),
            ],
        ),
    ]
