# Generated by Django 5.1.7 on 2025-05-15 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab4App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lab4App.publishinghouse'),
        ),
        migrations.AlterField(
            model_name='publishinghouse',
            name='website',
            field=models.CharField(max_length=100),
        ),
    ]
